// generated by sulaptomap. It's oke to modify, don't be shy.
package packagesample

func (so *SomeStructB) ToMap(mapper map[string]any) {

	if so.Id != 0 {
		mapper["id"] = so.Id
	}

	if so.Name != "" {
		mapper["name"] = so.Name
	}

	if so.Amount != nil {
		mapper["amount"] = *so.Amount
	}

	if so.Currency != nil {
		mapper["currency"] = *so.Currency
	}

	if so.CreatedBy != "" {
		mapper["created_by"] = so.CreatedBy
	}

	if so.UpdatedBy != "" {
		mapper["updated_by"] = so.UpdatedBy
	}

	if so.CreatedAt.Valid {
		mapper["created_at"] = so.CreatedAt.Time
	}

	if so.UpdatedAt.Valid {
		mapper["updated_at"] = so.UpdatedAt.Time
	}

}

func (so *SomeStructB) FieldsLen() int {
	return 8
}
